export default {
  decisionPoints: [
    {
      name: 'Boundary Proximity',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'BP',
    },
    {
      name: 'CIS-CTI Words of Estimative Probability',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'CIS_WEP',
    },
    {
      name: 'Do, Schedule, Delegate, Delete',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'IKE',
    },
    {
      name: 'LowMediumHigh',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'LMH',
    },
    {
      name: 'Median Split',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'MEDIAN',
    },
    {
      name: 'MoSCoW',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'MSCW',
    },
    {
      name: 'Probability Scale in 2 equal levels, ascending',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'P_2A',
    },
    {
      name: 'Probability Scale in 5 equal levels, ascending',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'P_5A',
    },
    {
      name: 'Probability Scale in 5 weighted levels, ascending',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'P_5X',
    },
    {
      name: 'Quartiles',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'QUARTILES',
    },
    {
      name: 'Quintiles',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'QUINTILES',
    },
    {
      name: 'Value, Complexity',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'VALUE_COMPLEXITY',
    },
    {
      name: 'YesNo',
      namespace: 'basic',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'YN',
    },
    {
      name: 'CISA Levels',
      namespace: 'cisa',
      schemaVersion: '2.0.0',
      version: '1.1.0',
      key: 'CISA',
    },
    {
      name: 'In KEV',
      namespace: 'cisa',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'KEV',
    },
    {
      name: 'Mission Prevalence',
      namespace: 'cisa',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'MP',
    },
    {
      name: 'Access Complexity',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'AC',
    },
    {
      name: 'Access Complexity',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'AC',
    },
    {
      name: 'Access Vector',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'AV',
    },
    {
      name: 'Access Vector',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'AV',
    },
    {
      name: 'Attack Complexity',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.0',
      key: 'AC',
    },
    {
      name: 'Attack Complexity',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.1',
      key: 'AC',
    },
    {
      name: 'Attack Requirements',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'AT',
    },
    {
      name: 'Attack Vector',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.0',
      key: 'AV',
    },
    {
      name: 'Attack Vector',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.1',
      key: 'AV',
    },
    {
      name: 'Authentication',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'Au',
    },
    {
      name: 'Authentication',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'Au',
    },
    {
      name: 'Automatable',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'AU',
    },
    {
      name: 'Availability Impact',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'A',
    },
    {
      name: 'Availability Impact',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'A',
    },
    {
      name: 'Availability Impact to the Subsequent System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'SA',
    },
    {
      name: 'Availability Impact to the Vulnerable System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.0',
      key: 'VA',
    },
    {
      name: 'Availability Requirement',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'AR',
    },
    {
      name: 'Availability Requirement',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.0',
      key: 'AR',
    },
    {
      name: 'Availability Requirement',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.1',
      key: 'AR',
    },
    {
      name: 'Availability Requirement (without Not Defined)',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.1',
      key: 'AR_NoX',
    },
    {
      name: 'Collateral Damage Potential',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'CDP',
    },
    {
      name: 'Collateral Damage Potential',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'CDP',
    },
    {
      name: 'Confidentiality Impact',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'C',
    },
    {
      name: 'Confidentiality Impact',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'C',
    },
    {
      name: 'Confidentiality Impact to the Subsequent System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'SC',
    },
    {
      name: 'Confidentiality Impact to the Vulnerable System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.0',
      key: 'VC',
    },
    {
      name: 'Confidentiality Requirement',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'CR',
    },
    {
      name: 'Confidentiality Requirement',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.0',
      key: 'CR',
    },
    {
      name: 'Confidentiality Requirement',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.1',
      key: 'CR',
    },
    {
      name: 'Confidentiality Requirement (without Not Defined)',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.1',
      key: 'CR_NoX',
    },
    {
      name: 'CVSS Qualitative Severity Rating Scale',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'CVSS',
    },
    {
      name: 'Equivalence Set 1',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'EQ1',
    },
    {
      name: 'Equivalence Set 2',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'EQ2',
    },
    {
      name: 'Equivalence Set 3',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'EQ3',
    },
    {
      name: 'Equivalence Set 4',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'EQ4',
    },
    {
      name: 'Equivalence Set 5',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'EQ5',
    },
    {
      name: 'Equivalence Set 6',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'EQ6',
    },
    {
      name: 'Exploit Code Maturity',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.2.0',
      key: 'E',
    },
    {
      name: 'Exploit Maturity',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'E',
    },
    {
      name: 'Exploit Maturity (without Not Defined)',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'E_NoX',
    },
    {
      name: 'Exploitability',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'E',
    },
    {
      name: 'Exploitability',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.0',
      key: 'E',
    },
    {
      name: 'Impact Bias',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'IB',
    },
    {
      name: 'Integrity Impact',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'I',
    },
    {
      name: 'Integrity Impact',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'I',
    },
    {
      name: 'Integrity Impact to the Subsequent System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'SI',
    },
    {
      name: 'Integrity Impact to the Vulnerable System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.0',
      key: 'VI',
    },
    {
      name: 'Integrity Requirement',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'IR',
    },
    {
      name: 'Integrity Requirement',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.0',
      key: 'IR',
    },
    {
      name: 'Integrity Requirement',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.1',
      key: 'IR',
    },
    {
      name: 'Integrity Requirement (without Not Defined)',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.1',
      key: 'IR_NoX',
    },
    {
      name: 'Modified Attack Complexity',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.0',
      key: 'MAC',
    },
    {
      name: 'Modified Attack Complexity',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.1',
      key: 'MAC',
    },
    {
      name: 'Modified Attack Requirements',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'MAT',
    },
    {
      name: 'Modified Attack Vector',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.0',
      key: 'MAV',
    },
    {
      name: 'Modified Attack Vector',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.1',
      key: 'MAV',
    },
    {
      name: 'Modified Availability Impact',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'MA',
    },
    {
      name: 'Modified Availability Impact to the Subsequent System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'MSA',
    },
    {
      name: 'Modified Availability Impact to the Subsequent System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.1',
      key: 'MSA',
    },
    {
      name: 'Modified Availability Impact to the Subsequent System (without Not Defined)',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.1',
      key: 'MSA_NoX',
    },
    {
      name: 'Modified Availability Impact to the Vulnerable System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.0',
      key: 'MVA',
    },
    {
      name: 'Modified Confidentiality Impact',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'MC',
    },
    {
      name: 'Modified Confidentiality Impact to the Subsequent System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'MSC',
    },
    {
      name: 'Modified Confidentiality Impact to the Subsequent System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.1',
      key: 'MSC',
    },
    {
      name: 'Modified Confidentiality Impact to the Vulnerable System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.0',
      key: 'MVC',
    },
    {
      name: 'Modified Integrity Impact',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'MI',
    },
    {
      name: 'Modified Integrity Impact to the Subsequent System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'MSI',
    },
    {
      name: 'Modified Integrity Impact to the Subsequent System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.1',
      key: 'MSI',
    },
    {
      name: 'Modified Integrity Impact to the Subsequent System (without Not Defined)',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.1',
      key: 'MSI_NoX',
    },
    {
      name: 'Modified Integrity Impact to the Vulnerable System',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '3.0.0',
      key: 'MVI',
    },
    {
      name: 'Modified Privileges Required',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'MPR',
    },
    {
      name: 'Modified Privileges Required',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.1',
      key: 'MPR',
    },
    {
      name: 'Modified Scope',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'MS',
    },
    {
      name: 'Modified User Interaction',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'MUI',
    },
    {
      name: 'Modified User Interaction',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'MUI',
    },
    {
      name: 'Privileges Required',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'PR',
    },
    {
      name: 'Privileges Required',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.1',
      key: 'PR',
    },
    {
      name: 'Provider Urgency',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'U',
    },
    {
      name: 'Recovery',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'R',
    },
    {
      name: 'Remediation Level',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'RL',
    },
    {
      name: 'Remediation Level',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.0',
      key: 'RL',
    },
    {
      name: 'Report Confidence',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'RC',
    },
    {
      name: 'Report Confidence',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.0',
      key: 'RC',
    },
    {
      name: 'Report Confidence',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'RC',
    },
    {
      name: 'Safety',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'SF',
    },
    {
      name: 'Scope',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'S',
    },
    {
      name: 'Target Distribution',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'TD',
    },
    {
      name: 'Target Distribution',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.1.0',
      key: 'TD',
    },
    {
      name: 'User Interaction',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'UI',
    },
    {
      name: 'User Interaction',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'UI',
    },
    {
      name: 'Value Density',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'V',
    },
    {
      name: 'Vulnerability Response Effort',
      namespace: 'cvss',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'RE',
    },
    {
      name: 'Automatable',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'A',
    },
    {
      name: 'Critical Software',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'CS',
    },
    {
      name: 'Decline, Track, Coordinate',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'COORDINATE',
    },
    {
      name: 'Decline, Track, Coordinate',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.1',
      key: 'COORDINATE',
    },
    {
      name: 'Defer, Scheduled, Out-of-Cycle, Immediate',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'DSOI',
    },
    {
      name: 'Exploitation',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'E',
    },
    {
      name: 'Exploitation',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.1.0',
      key: 'E',
    },
    {
      name: 'High Value Asset',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'HVA',
    },
    {
      name: 'Human Impact',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'HI',
    },
    {
      name: 'Human Impact',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '2.0.1',
      key: 'HI',
    },
    {
      name: 'Human Impact',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '2.0.2',
      key: 'HI',
    },
    {
      name: 'Mission and Well-Being Impact',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'MWI',
    },
    {
      name: 'Mission Impact',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'MI',
    },
    {
      name: 'Mission Impact',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'MI',
    },
    {
      name: 'Public Safety Impact',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'PSI',
    },
    {
      name: 'Public Safety Impact',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '2.0.1',
      key: 'PSI',
    },
    {
      name: 'Public Value Added',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'PVA',
    },
    {
      name: 'Public Well-Being Impact',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.1.0',
      key: 'PWI',
    },
    {
      name: 'Publish, Do Not Publish',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'PUBLISH',
    },
    {
      name: 'Report Credibility',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'RC',
    },
    {
      name: 'Report Public',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'RP',
    },
    {
      name: 'Safety Impact',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'SI',
    },
    {
      name: 'Safety Impact',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '2.0.0',
      key: 'SI',
    },
    {
      name: 'Supplier Cardinality',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'SC',
    },
    {
      name: 'Supplier Contacted',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'SCON',
    },
    {
      name: 'Supplier Engagement',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'SE',
    },
    {
      name: 'Supplier Involvement',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'SINV',
    },
    {
      name: 'System Exposure',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'EXP',
    },
    {
      name: 'System Exposure',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.1',
      key: 'EXP',
    },
    {
      name: 'Technical Impact',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'TI',
    },
    {
      name: 'Utility',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'U',
    },
    {
      name: 'Utility',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.1',
      key: 'U',
    },
    {
      name: 'Value Density',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'VD',
    },
    {
      name: 'Virulence',
      namespace: 'ssvc',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'V',
    },
    {
      name: 'theParanoids',
      namespace: 'x_com.yahooinc#prioritized-risk-remediation',
      schemaVersion: '2.0.0',
      version: '1.0.0',
      key: 'PARANOIDS',
    },
  ],
}
