export * from '../csaf_2_0/optionalTests.js'
export { default as optionalTest_6_2_21 } from './optionalTests/optionalTest_6_2_21.js'
export { default as optionalTest_6_2_22 } from './optionalTests/optionalTest_6_2_22.js'
export { default as optionalTest_6_2_23 } from './optionalTests/optionalTest_6_2_23.js'
export { default as optionalTest_6_2_25 } from './optionalTests/optionalTest_6_2_25.js'
export { default as optionalTest_6_2_26 } from './optionalTests/optionalTest_6_2_26.js'
export { default as optionalTest_6_2_27 } from './optionalTests/optionalTest_6_2_27.js'
