exports.informativeTest_6_3_1 = require('./informativeTests/informativeTest_6_3_1.js')
exports.informativeTest_6_3_2 = require('./informativeTests/informativeTest_6_3_2.js')
exports.informativeTest_6_3_3 = require('./informativeTests/informativeTest_6_3_3.js')
exports.informativeTest_6_3_4 = require('./informativeTests/informativeTest_6_3_4.js')
exports.informativeTest_6_3_5 = require('./informativeTests/informativeTest_6_3_5.js')
exports.informativeTest_6_3_6 = require('./informativeTests/informativeTest_6_3_6.js')
exports.informativeTest_6_3_7 = require('./informativeTests/informativeTest_6_3_7.js')
