export default {
  decisionPoints: [
    {
      name: 'Automatable',
      namespace: 'ssvc',
      version: '2.0.0',
      key: 'A',
    },
    { name: 'Exploitation', namespace: 'ssvc', version: '1.0.0', key: 'E' },
    {
      name: 'Exploitation',
      namespace: 'ssvc',
      version: '1.1.0',
      key: 'E',
    },
    { name: 'Human Impact', namespace: 'ssvc', version: '1.0.0', key: 'HI' },
    {
      name: 'Human Impact',
      namespace: 'ssvc',
      version: '2.0.0',
      key: 'HI',
    },
    {
      name: 'Human Impact',
      namespace: 'ssvc',
      version: '2.0.1',
      key: 'HI',
    },
    {
      name: 'Mission and Well-Being Impact',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'MWI',
    },
    { name: 'Mission Impact', namespace: 'ssvc', version: '1.0.0', key: 'MI' },
    {
      name: 'Mission Impact',
      namespace: 'ssvc',
      version: '2.0.0',
      key: 'MI',
    },
    {
      name: 'Public Safety Impact',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'PSI',
    },
    {
      name: 'Public Safety Impact',
      namespace: 'ssvc',
      version: '2.0.0',
      key: 'PSI',
    },
    {
      name: 'Public Safety Impact',
      namespace: 'ssvc',
      version: '2.0.1',
      key: 'PSI',
    },
    {
      name: 'Public Value Added',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'PVA',
    },
    {
      name: 'Public Well-Being Impact',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'PWI',
    },
    {
      name: 'Report Credibility',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'RC',
    },
    {
      name: 'Report Public',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'RP',
    },
    { name: 'Safety Impact', namespace: 'ssvc', version: '1.0.0', key: 'SI' },
    {
      name: 'Safety Impact',
      namespace: 'ssvc',
      version: '2.0.0',
      key: 'SI',
    },
    {
      name: 'Supplier Cardinality',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'SC',
    },
    {
      name: 'Supplier Contacted',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'SC',
    },
    {
      name: 'Supplier Engagement',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'SE',
    },
    {
      name: 'Supplier Involvement',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'SI',
    },
    {
      name: 'System Exposure',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'EXP',
    },
    {
      name: 'System Exposure',
      namespace: 'ssvc',
      version: '1.0.1',
      key: 'EXP',
    },
    {
      name: 'Technical Impact',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'TI',
    },
    {
      name: 'Utility',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'U',
    },
    { name: 'Utility', namespace: 'ssvc', version: '1.0.1', key: 'U' },
    {
      name: 'Value Density',
      namespace: 'ssvc',
      version: '1.0.0',
      key: 'VD',
    },
    { name: 'Virulence', namespace: 'ssvc', version: '1.0.0', key: 'V' },
  ],
}
