name: Run Tests
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
permissions:
  contents: read
  actions: read
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - run: sudo apt-get install hunspell
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start language tool
        run: docker compose -f dev/languagetool/compose.yml up -d
      - name: Wait for app start
        uses: ifaxity/wait-on-action@v1
        with:
          delay: 1
          timeout: 120000
          resource: http://localhost:8010/v2/languages
      - run: npm ci
      - run: npm run test-report
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
      - run: npm run test-coverage-lcov
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > ./pr_number
      - uses: actions/upload-artifact@v6
        if: success() || failure()
        with:
          name: test-results-${{ matrix.node-version }}
          path: |
            test-results.xml
            coverage
            pr_number

  test-browser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npm run test:browser
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
